version: "3"
services:
  postgres-db:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=simple_blog_api

  api:
    depends_on:
      - postgres
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    image: piechucker/simple_blog_api
    environment:
        - POSTGRES_HOST=postgres-db
        - POSTGRES_PORT=5432
        - POSTGRES_DB=simple_blog_api
        - POSTGRES_USERNAME=postgres
        - POSTGRES_PASSWORD=postgres_password
        
    ports:
      - "8082:3000"